services:
  formatter:
    build:
      context: ${HOST_PROJECT_PATH:-.}/..
      dockerfile: reformat/Dockerfile
    image: cloud-volume-actions-reformat:latest
    working_dir: /workspace
    volumes:
      - ${HOST_PROJECT_PATH:-..}:/workspace
    command: ./reformat/reformat.sh
